# Generated by Django 4.2.5 on 2024-05-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_sessioninstance_aircrafts_sessioninstance_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationsession',
            name='post_type',
            field=models.CharField(choices=[('all', 'All Users'), ('users', 'Selected Users')], default='all', max_length=10),
        ),
    ]
