# Generated by Django 4.2.5 on 2024-05-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_simulationsession_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='channel_id',
            field=models.CharField(default='', max_length=250),
        ),
    ]
