# Generated by Django 4.2.5 on 2024-05-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_simulationsession_controllable_aircraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
