# Generated by Django 4.2.5 on 2024-05-16 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_clashpositions_simulationsession_clash_positions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClashPositions',
            new_name='ClashPosition',
        ),
    ]
