# Generated by Django 4.2.5 on 2024-05-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_clashpositions_clashposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationsession',
            name='simmulation_time',
            field=models.IntegerField(default=360),
        ),
    ]
