# Generated by Django 4.2.5 on 2024-05-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_simulationsession_simmulation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationsession',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simulationsession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
