# Generated by Django 4.2.5 on 2024-05-27 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0006_aircraft_aircraft_type'),
        ('users', '0013_alter_simulationsession_end_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioninstance',
            name='controllable_aircraft',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controllable_aircraft', to='aircraft.aircraft'),
        ),
        migrations.AlterField(
            model_name='simulationsession',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('started', 'Started'), ('paused', 'Paused'), ('closed', 'Closed')], default='created', max_length=10),
        ),
    ]
