# Generated by Django 4.2.5 on 2024-05-06 05:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAircraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('angle', models.IntegerField()),
                ('altitude', models.DecimalField(decimal_places=4, max_digits=10)),
                ('velocity', models.IntegerField()),
                ('start_pos_lng', models.DecimalField(decimal_places=16, max_digits=20)),
                ('start_pos_lat', models.DecimalField(decimal_places=16, max_digits=20)),
                ('end_pos_lng', models.DecimalField(decimal_places=16, max_digits=20)),
                ('end_pos_lat', models.DecimalField(decimal_places=16, max_digits=20)),
                ('cur_pos_lng', models.DecimalField(decimal_places=16, max_digits=20)),
                ('cur_pos_lat', models.DecimalField(decimal_places=16, max_digits=20)),
                ('mode_s_add', models.CharField(max_length=20)),
                ('ssr_code', models.CharField(max_length=20)),
                ('nic_value', models.CharField(max_length=20)),
                ('call_sign', models.CharField(max_length=20)),
                ('emergency_Indic', models.CharField(max_length=20)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aircraft.adminaircraft')),
            ],
        ),
    ]
