# Generated by Django 4.2.5 on 2024-05-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='aircraft_id',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
