# Generated by Django 4.2.5 on 2024-05-08 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0002_aircraft_aircraft_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='call_sign',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='emergency_Indic',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='mode_s_add',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='nic_value',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='ssr_code',
        ),
    ]
