# Generated by Django 4.2.5 on 2024-05-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0004_aircraft_max_altitude_aircraft_max_velocity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='angle',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
