# Generated by Django 4.2.5 on 2024-05-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0005_alter_aircraft_angle'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='aircraft_type',
            field=models.CharField(choices=[('A', 'Admin'), ('U', 'User')], default='A', max_length=1),
        ),
    ]
